version: '3'
services:
  frontend:
    image: ui-build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    image: server-build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"  
